[[Bar]]
Name = "Main"

# dimensions in pixels
Width = 1000
Height = 50

# horizontal center
Center = true

# offsets will be applied
# on top of `center` if
# it's enabled
OffsetX = 0
OffsetY = 0

Widgets = [
	"Clock"
]

# can be around, between, none
WidgetSpacing = "around"

[[Widgets]]
Name = "Clock"

# built-in module
Type = "Time"
# strftime-style format
Format = "%H:%M"

# defaults to white and black
# respectively
ForegroundNormal = "#ffffff"
BackgroundNormal = "#000000"

# defaults to normals
ForegroundHover = "#ffffff"
BackgroundHover = "#000000"
